'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); const result = mode === 'sign-up' ? await authClient.signUp.email({ email, password, name }) : await authClient.signIn.email({ email, password }); setLoading(false); if (result.error) { setError('Unable to authenticate. Check your details and try again.'); return }; router.push('/'); router.refresh() }
  return <form onSubmit={submit} className="w-full max-w-sm space-y-4 rounded-xl border border-border bg-card p-6 shadow-sm"><div><h1 className="text-xl font-semibold">{mode === 'sign-up' ? 'Create your ListShield account' : 'Welcome back'}</h1><p className="mt-2 text-sm text-muted-foreground">{mode === 'sign-up' ? 'Protect your shop with private, secure audits.' : 'Sign in to access your workspace.'}</p></div>{mode === 'sign-up' && <input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />}<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm" /><input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />{error && <p className="text-sm text-destructive">{error}</p>}<button disabled={loading} className="w-full rounded-md bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{loading ? 'Please wait…' : mode === 'sign-up' ? 'Create account' : 'Sign in'}</button><a href={mode === 'sign-up' ? '/sign-in' : '/sign-up'} className="block text-center text-xs text-muted-foreground hover:text-foreground">{mode === 'sign-up' ? 'Already have an account? Sign in' : 'Need an account? Create one'}</a></form>
}
